name: Actions with Bors

on:
  push:
    branches:
      [staging1, trying1]

  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 5

  checks:
    # name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 5
