name: Actions with Bors

on:
  push:

##
jobs:
  main_job:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 5

  checks:
    name: Run all checks
    needs: main_job
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

  checks2:
    name: check2
    if: main_job != 
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 10
