name: Actions wo Bors

on:
  push:
    branches:
      [master]
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  main_job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 10

  checks:
    name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 10
