name: Test CI
on:
  pull_request:

jobs:
  # JOB to run change detection
  selection:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      dart: ${{ steps.filter.outputs.dart }}
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          filters: |
            dart:
              - 'testFolder/**'
              - 'testFolder2/**'
            rust:
              - 'testFolder2/**'
    #TEST 1
  cargo-format:
    name: cargo-format
    needs: selection
    if: ${{ needs.selection.outputs.dart == 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 0
  cargo-test:
    name: cargo-test
    needs: [selection,cargo-test2]
    if: ${{always()}}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: |
          if ( ${{needs.cargo-test2.result}} == 'failure')
            then
            exit 1
          fi
      - run: echo Sigue
  cargo-ok:
    name: cargo-ok
    needs: 
      - cargo-format
      - cargo-test
    if: ${{always()}}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: |
          if (${{needs.cargo-format.result == 'success' }} && ${{needs.cargo-test.result == 'success'}})
          then
            exit 0
          else
            exit 1
          fi

  #   #TEST2
  cargo-format2:
    name: cargo-format2
    needs: selection
    if: ${{ needs.selection.outputs.rust == 'true'}}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 0
  cargo-test2:
    name: cargo-test2
    needs: selection
    if: ${{ needs.selection.outputs.rust == 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 0
  cargo-ok2:
    name: cargo-ok2
    needs: 
      - cargo-format2
      - cargo-test2
    if: ${{ needs.selection.outputs.rust }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 0

  ci-ok:
    name: ci-ok
    needs: [selection, cargo-ok2, cargo-ok]
    if: ${{always()}} 
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          if (${{ needs.selection.outputs.dart == 'true'}} || ${{ needs.selection.outputs.rust == 'true' }} )
          then
            if (( (${{needs.selection.outputs.dart != 'true'}} || ${{needs.cargo-ok.result == 'success'}}) && (${{needs.selection.outputs.rust != 'true'}} || ${{needs.cargo-ok2.result == 'success'}}) ) || 
            (${{needs.selection.outputs.dart == 'true'}} && ${{needs.cargo-ok2.result == 'success'}} && ${{needs.selection.outputs.rust != 'true'}}))
            then
              exit 0
            else
              exit 1
            fi
          else
            exit 1
          fi
            

      
