name: Xayn PR to develop checks and tests

on:
  pull_request:
    branches:
      - master
    types: [synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

env:
  flutter_channel: 'stable'
  flutter_version: '2.5.1'
  java_version: '12.x'
  ios_device: 'iPhone 11 Pro (14.5)'
jobs:  
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          paths_ignore: '["**/README.md","**/docs/**",".github/workflows/actions.yml",".DS_Store"]'

  main_job:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.pre_job.outputs.should_skip }}
      - run: echo "Running slow tests..." && sleep 30