name: Actions with Bors

on:
  push:

##
jobs:
  main_job:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 5

  checks:
    # name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 5
