name: Actions with Bors

on:
  push:

jobs:
  download:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        continue-on-error: true
        run: |
          exit 1                    
      - name: retry
        continue-on-error: true
        if: steps.test.outcome=='failure'         # check the step outcome, retry 1st time
        run: |
          exit 1                                
      - name: retry 2
        continue-on-error: true
        id: retry2
        if: steps.retry1.outcome=='failure'   # check the step outcome, retry 2nd time
        run: |
          echo retry 2nd time
          exit 1     
      - name: retry 3
        continue-on-error: true
        id: retry3
        if: steps.retry2.outcome=='failure'      # check the step outcome, retry 3rd time
        run: |
          echo retry 3rd time                
      - name: set the status              # set the workflow status if command failed
        run: |
          echo ${{steps.test.outcome}}
          echo fine
