name: Test CI
on:
  pull_request:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      test: ${{ steps.filter.outputs.test }}
      test2: ${{ steps.filter.outputs.test2 }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            test:
              - 'testFolder/**'
            test2:
              - 'testFolder2/**'
  
  cargo-format:
    name: cargo-format
    needs: changes
    if: ${{ needs.changes.outputs.test }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 1

  cargo-format2:
    name: cargo-format2
    needs: changes
    if: ${{ needs.changes.outputs.test2 }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: exit 1

  cargo:
    needs: [changes, cargo-format, cargo-format2]
    if: ${{always()}}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Both of them
        if: ${{ needs.changes.outputs.test  }} || ${{ needs.changes.outputs.test2 }}
        run: |
          if ( ${{ needs.changes.outputs.test }} && ${{ needs.changes.outputs.test2 }} && ${{ needs.cargo-format.result == 'success'}} && ${{ needs.cargo-format2.result == 'success'}} )
          then
            exit 0
          elif ( ${{ needs.changes.outputs.test }} && ${{ needs.cargo-format.result == 'success'}} && ${{ !needs.changes.outputs.test2 }} )
          then
            exit 0
          elif ( ${{ needs.changes.outputs.test2 }} && ${{ needs.cargo-format2.result == 'success'}} && ${{ !needs.changes.outputs.test }} )
          then
            exit 0
          else
            exit 1
          fi
