name: Test CI
on:
  pull_request:

jobs:
  dev-ci:
    uses: jorge-cr-13/test2-2/.github/workflows/ci_reusable_wf.yml@master

  ci-ok:
    name: ci-ok
    needs: [dev-ci]
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          echo ${{needs.dev-ci.outputs.dart}}
          if (( (${{needs.dev-ci.outputs.dart != 'true'}} || ${{needs.cargo-ok.result == 'success'}}) && (${{needs.dev-ci.outputs.rust != 'true'}} || ${{needs.cargo-ok2.result == 'success'}}) ) || 
          (${{needs.dev-ci.outputs.dart == 'true'}} && ${{needs.cargo-ok2.result == 'success'}} && ${{needs.dev-ci.outputs.rust != 'true'}}))
          then
            exit 0
          else
            exit 1
          fi
            

      
