name: Test CI
on:
  push:
    branches-ignore:
      - 'master'
      - '_bors*'
    paths:
      - 'testFolder/**'
jobs:
  cargo-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: echo Hola
