name: Xayn PR to develop checks and tests

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

env:
  flutter_channel: 'stable'
  flutter_version: '2.5.1'
  java_version: '12.x'
  ios_device: 'iPhone 11 Pro (14.5)'
jobs:
  main_job:
    if: (needs.skip_jobs.outputs.should_skip != 'true')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 30

  checks:
    name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    timeout-minutes: 15
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v2
