name: Xayn PR to develop checks and tests

on:
  push:
    branches:
      [master, staging, trying]
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 5

  checks:
    # name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 5
