name: Test CI
on:
  pull_request:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      test: ${{ steps.filter.outputs.test }}
      test2: ${{ steps.filter.outputs.test2 }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            test:
              - 'testFolder/**'
            test2:
              - 'testFolder2/**'
  
  cargo-format:
    needs: changes
    if: ${{ needs.changes.outputs.test == 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: echo Hola

  cargo-format2:
    needs: changes
    if: ${{ needs.changes.outputs.test2 == 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: echo Hola2

  cargo:
    needs: [changes, cargo-format, cargo-format2]
    if: ${{ needs.changes.outputs.test == 'true' }} || ${{ needs.changes.outputs.test2 == 'true' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - if: ${{ needs.changes.outputs.test == 'true' }} && ${{ needs.changes.outputs.test2 == 'true' }}
        run: |
          if [ ${{ needs.cargo-format.status == 'success' }} && ${{ needs.cargo-format2.status == 'success' }} ]
          then
            exit 0
          else
            exit 1
          fi


