name: Test CI
on:
  pull_request:

jobs:
  dev-ci:
    uses: jorge-cr-13/test2-2/.github/workflows/ci_reusable_wf.yml@master

  ci-ok:
    name: ci-ok
    needs: [dev-ci]
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          echo ${{needs.dev-ci.outputs.cargo-ok}}
          echo ${{needs.dev-ci.outputs.cargo-ok2}}
          if (( (${{needs.dev-ci.outputs.dart_output != 'true'}} || ${{needs.dev-ci.outputs.cargo-ok == 'success'}}) && (${{needs.dev-ci.outputs.rust != 'true'}} || ${{needs.dev-ci.outputs.cargo-ok2 == 'success'}}) ) || 
          (${{needs.dev-ci.outputs.dart_output == 'true'}} && ${{needs.dev-ci.outputs.cargo-ok2 == 'success'}} && ${{needs.dev-ci.outputs.rust != 'true'}}))
          then
            exit 0
          else
            exit 1
          fi
            

      
