name: Actions wo Bors

on:
  push:
    branches:
      [master]

  workflow_dispatch:

jobs:
  main_job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 10

  checks:
    name: Run all checks
    runs-on: ubuntu-latest
    needs: main_job
    steps:
      - run: echo "Running slow tests..." && sleep 10
