name: Test CI
on:
  push:
    branches:
      - '_bors_staging'
      - '_bors_trying'
    paths:
      - 'testFolder/**'
jobs:
  cargo-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: echo Hola
