name: Test CI
on:
  push:
    branches-ignore:
      - '_bors_staging'
      - '_bors_trying'
    paths:
      - 'testFolder2/**'
jobs:
  cargo-format2:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: echo Hola2 bors
